# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deployment@Github

on:
  release:
    type: [released, prereleased]

env:
  GH_USERNAME: ${{ secrets.GH_USERNAME }}
  GH_PASSWORD: ${{ secrets.GH_PASSWORD }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -s ./.mvn/settings.xml -Pgithub -B deploy --file pom.xml
